apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-docs-pipeline
spec:
#  resources:
#    - name: markdown-documents
#      type: git
  tasks:
    - name: build-docs
      taskRef:
        name: build-docs
#      resources:
#        inputs:
#          - name: markdown-documents
#            resource: markdown-documents
