apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-docs-run
spec:
  pipelineRef:
    name: build-docs-pipeline
  workspaces:
    - name: files
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200M
    - name: docker-credentials
      secret:
        secretName: docker-credentials
  params:
    - name: repository
      value: "https://github.com/schneefisch/tekton-mkdoks-pipeline-sample"
    - name: repository-name
      value: "tekton-mkdoks-pipeline-sample"
    - name: image-reference
      value: "demo-documentation"
    - name: image-tag
      value: "v0.1"
