apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-docs-run
spec:
  pipelineRef:
    name: build-docs-pipeline
  workspaces:
    - name: files
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200M
