apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docs
spec:
  params:
    - name: repository
      description: Git Repo URL
    - name: repository-name
      description: Git Repo name
  workspaces:
    - name: files
  steps:
    - name: checkout
      image: alpine
      env:
        - name: REPOSITORY
          value: $(params.repository)
      script: |
        #!/bin/sh
        # install git
        apk update && apk add git && git --version
        
        # checkout repo
        echo "Checkout Git repository: ${REPOSITORY}"
        cd $(workspaces.files.path) && git clone -q ${REPOSITORY}

    - name: setup
      image: python:3.9.14
      env:
        - name: REPOSITORYNAME
          value: $(params.repository-name)
      script: |
        #!/bin/sh
        echo "Is pip still there?"
        pip --version
        
        # install mkdocs
        pip install mkdocs
        mkdocs --version
        
        echo "Files"
        ls -al $(workspaces.files.path)/$(params.repository-name)
        
        # mkdocs
        echo "\nBuild docs"
        mkdocs build -f $(workspaces.files.path)/$(params.repository-name)/mkdocs.yaml -d $(workspaces.files.path)/$(params.repository-name)/site/
        
        echo "\nGenerated resources"
        ls -al $(workspaces.files.path)/$(params.repository-name)/site
