apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-docs-pipeline
spec:
  workspaces:
    - name: files
  tasks:
    - name: build-docs
      taskRef:
        name: build-docs
      workspaces:
        - name: files
      params:
        - name: repository
          value: https://github.com/schneefisch/tekton-mkdoks-pipeline-sample
        - name: repository-name
          value: tekton-mkdoks-pipeline-sample
