# Create a copy of this secrets-file and insert your Docker-Hub Access-Key in it.
# The data must be base64 encoded!
# Create the secret in your kubernetes by running
# kubectl apply -f secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
data:
  config.json: efuJAmF1...
